### ISSUE TITLE
Integration with Flysystem?

### ISSUE THREAD

**Issue by cassianotartari** [artgris/FileManagerBundle#5]
Hey!

First of all, thank you for such a great public project!

I want to integrate with Amazon S3, do you think it is possible to integrate with Flysystem or Gaufrette throw the service configuration that you provide? Or maybe fork this project.

Thanks!

**Comment by cassianotartari** [comment]
ping @artgris

**Comment by artgris** [comment]
Hi @cassianotartari , Thank you,

About your integration, I'm not familiar with Flysystem and Gaufrette but I'don't think you can easily integrate my bundle with Gaufrette because I'm using Symfony FileSystem and not Gaufrette FileSystem. The service Configuration in my bundle is only useful to get a dynamic conf (config.yml). 
Maybe if you fork project and replace Symfony filesystem access by gaufrette filesystem, that could work.

**Comment by cassianotartari** [comment]
Thank you @artgris! In the next days I'll fork your project and try to do it, is the next activity from my actual sprint, create a asset manager for s3

**Comment by rvmourik** [comment]
@cassianotartari did you ever fork this project for integrating it with Flysystem?

**Comment by cassianotartari** [comment]
@rvmourik no, a dev from my team did something, it's here https://github.com/moumenashaar/FileManagerBundle I did not make a code review so I'm not sure how it is integrated.

**Comment by rvmourik** [comment]
@cassianotartari thanks, will have a look :-)
